### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by steve-tregidgo** [smkiewel/unique-sum-helpers#1]
I like this tool very much, but it is a big blast of white light when I switch to it on my monitor (because it's just one more tab in a maximised browser on a fairly big monitor). Is it possible to get a dark mode implemented? I'd be very happy with even a checkbox to enable it, although even better would be a tri-state control that defaulted to making a 'prefers-color-scheme' media query.

Thanks again for a terrific helper which is very easy to use.

**Comment by smkiewel** [comment]
Ask and ye shall receive. While I did just do a simple checkbox for it, I think it'll meet your needs. Let me know if it needs tweaking.

**Comment by smkiewel** [comment]
I've done a step better than just "make the background not blind you". You can thank rangsk. Full dark mode is enabled. And the setting is sticky, so it'll remember it for next time, and it also checks to see if your browser is set to prefer dark mode. Hope this meets your needs!

**Comment by steve-tregidgo** [comment]
Superb! Thanks so much for that addition; it's much appreciated and will be
massively easier on the eyes.

(Apologies for the late reply - looks like I missed this being implemented
two weeks ago thanks to a surfeit of emails. I wasn't trying to encourage
more work by withholding praise!)

Cheers

**Comment by smkiewel** [comment]
Glad you like it! And no, you didn't make more work for me... I accidentally broke mobile when I added the dark mode toggle and didn't notice until today. So since I was fixing that, I went ahead and did it all the right way. 

Let me know if there is anything else that could help!
